# Generated by Django 4.2.4 on 2023-08-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_1",
                    models.TextField(blank=True, null=True, verbose_name="Answer1"),
                ),
                (
                    "answer_2",
                    models.TextField(blank=True, null=True, verbose_name="Answer2"),
                ),
                (
                    "answer_3",
                    models.TextField(blank=True, null=True, verbose_name="Answer3"),
                ),
                (
                    "answer_4",
                    models.TextField(blank=True, null=True, verbose_name="Answer4"),
                ),
                (
                    "answer_5",
                    models.TextField(blank=True, null=True, verbose_name="Answer5"),
                ),
                (
                    "answer_6",
                    models.TextField(blank=True, null=True, verbose_name="Answer6"),
                ),
                (
                    "answer_7",
                    models.TextField(blank=True, null=True, verbose_name="Answer7"),
                ),
                (
                    "answer_8",
                    models.TextField(blank=True, null=True, verbose_name="Answer8"),
                ),
                (
                    "answer_9",
                    models.TextField(blank=True, null=True, verbose_name="Answer9"),
                ),
                (
                    "answer_10",
                    models.TextField(blank=True, null=True, verbose_name="Answer10"),
                ),
            ],
        ),
    ]
